# SPDX-License-Identifier: BSL-1.0
# Run as: cmake -P tests/docs/test_docs.cmake (requires Doxygen and Ninja).
cmake_minimum_required(VERSION 3.24)
get_filename_component(toolkit_source "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
string(RANDOM LENGTH 16 ALPHABET 0123456789abcdef test_id)
set(test_root "${toolkit_source}/build/docs-${test_id}")

foreach(case default extended custom missing-input malformed-option multiline-option
    missing-input-value missing-option-value)
    set(source "${test_root}/${case}/source with spaces")
    set(binary "${test_root}/${case}/build with spaces")
    file(MAKE_DIRECTORY "${source}")
    file(COPY "${CMAKE_CURRENT_LIST_DIR}/fixtures/" DESTINATION "${source}")
    execute_process(COMMAND "${CMAKE_COMMAND}" -S "${source}" -B "${binary}" -G Ninja
        "-DTOOLKIT_SOURCE=${toolkit_source}" "-DCASE=${case}"
        RESULT_VARIABLE result OUTPUT_VARIABLE out ERROR_VARIABLE err)
    if(case MATCHES "^(missing-|malformed-|multiline-)")
        if(case STREQUAL "missing-input")
            set(expected "cpp-library: Documentation input does not exist")
        elseif(case STREQUAL "missing-input-value")
            set(expected "cpp_library_setup: DOCS_INPUTS requires a value")
        elseif(case STREQUAL "missing-option-value")
            set(expected "cpp_library_setup: DOCS_OPTIONS requires a value")
        else()
            set(expected "cpp-library: DOCS_OPTIONS requires single-line Doxygen assignments")
        endif()
        string(FIND "${out}\n${err}" "${expected}" diagnostic)
        if(result EQUAL 0 OR diagnostic LESS 0)
            message(FATAL_ERROR "${case}: Expected '${expected}':\n${out}\n${err}")
        endif()
    else()
        if(NOT result EQUAL 0)
            message(FATAL_ERROR "${case}: Configure failed:\n${out}\n${err}")
        endif()
        execute_process(COMMAND "${CMAKE_COMMAND}" --build "${binary}" --target docs
            RESULT_VARIABLE result OUTPUT_VARIABLE out ERROR_VARIABLE err)
        if(NOT result EQUAL 0)
            message(FATAL_ERROR "${case}: Doxygen failed:\n${out}\n${err}")
        endif()
        file(READ "${binary}/html/index.html" index)
        if(case STREQUAL "default")
            string(FIND "${index}" "Documentation fixture" brief)
        else()
            string(FIND "${index}" "Customized documentation" brief)
            string(FIND "${index}" "Extra fixture content" page)
            if(page LESS 0)
                message(FATAL_ERROR "${case}: Additional main page is missing")
            endif()
        endif()
        if(brief LESS 0)
            message(FATAL_ERROR "${case}: Project brief is missing")
        endif()
        if(case STREQUAL "default" OR case STREQUAL "extended")
            foreach(symbol hidden extra)
                set(page "${binary}/html/structfixture_1_1${symbol}.html")
                if(case STREQUAL "extended" AND EXISTS "${page}")
                    message(FATAL_ERROR "Excluded symbol is present: ${symbol}")
                elseif(case STREQUAL "default" AND NOT EXISTS "${page}")
                    message(FATAL_ERROR "Default documentation lost a public symbol: ${symbol}")
                endif()
            endforeach()
        endif()
        if(case STREQUAL "extended")
            if(NOT EXISTS "${binary}/html/group__extra__group.html")
                message(FATAL_ERROR "Absolute input group is missing")
            endif()
        endif()
        if(case STREQUAL "custom")
            string(FIND "${index}" "Legacy configuration" legacy)
            if(legacy LESS 0)
                message(FATAL_ERROR "Custom Doxyfile compatibility was lost")
            endif()
        endif()
    endif()
    message(STATUS "PASS documentation ${case}")
endforeach()

file(REMOVE_RECURSE "${test_root}")
