# SPDX-License-Identifier: BSL-1.0
#
# Run as: cmake -P tests/install/test_nested_install.cmake
# Requires a C++ compiler and Ninja (on Windows, run in a VS developer environment).
cmake_minimum_required(VERSION 3.24)

get_filename_component(toolkit_source "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
if(NOT DEFINED test_root)
    string(RANDOM LENGTH 16 ALPHABET 0123456789abcdef test_id)
    set(test_root "${toolkit_source}/build/nested-install-${test_id}")
endif()
set(failed_cases)
find_program(ctest NAMES ctest REQUIRED)

# Executes real build tools; any unexpected failure retains the exact command output.
function(run_command)
    execute_process(COMMAND ${ARGN}
        RESULT_VARIABLE result OUTPUT_VARIABLE out ERROR_VARIABLE err)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Command failed (${result}): ${ARGN}\n${out}\n${err}")
    endif()
    if(err)
        message(STATUS "Command diagnostics: ${ARGN}\n${err}")
    endif()
endfunction()

# Checks generated/installed package artifacts, including the dependency direction.
function(check_package prefix package present dependencies)
    set(config_dir "${prefix}/lib/cmake/stlab-${package}")
    foreach(suffix Config.cmake ConfigVersion.cmake Targets.cmake)
        set(path "${config_dir}/stlab-${package}${suffix}")
        if(present AND NOT EXISTS "${path}")
            message(FATAL_ERROR "Missing selected package artifact: ${path}")
        elseif(NOT present AND EXISTS "${path}")
            message(FATAL_ERROR "Unselected package artifact installed: ${path}")
        endif()
    endforeach()
    if(present)
        file(READ "${config_dir}/stlab-${package}Config.cmake" config)
        string(REGEX MATCHALL "find_dependency\\([^\n]*\\)" actual "${config}")
        if(NOT "${actual}" STREQUAL "${dependencies}")
            message(FATAL_ERROR "stlab-${package} dependencies: expected '${dependencies}', got '${actual}'")
        endif()
    endif()
endfunction()

# Each case has private source copies: toolkit template initialization must never mutate fixtures.
function(run_case name parent_installed leaf_installed shared)
    set(case_root "${test_root}/${name}")
    set(source "${case_root}/source")
    set(binary "${case_root}/build")
    set(prefix "${case_root}/prefix")
    file(MAKE_DIRECTORY "${source}")
    file(COPY "${CMAKE_CURRENT_LIST_DIR}/fixtures/nested/" DESTINATION "${source}")
    run_command("${CMAKE_COMMAND}" -S "${source}" -B "${binary}" -G Ninja
        "-DTOOLKIT_SOURCE=${toolkit_source}" "-DBUILD_SHARED_LIBS=${shared}" ${ARGN})
    run_command("${CMAKE_COMMAND}" --build "${binary}")
    run_command("${CMAKE_COMMAND}" --install "${binary}" --prefix "${prefix}")
    check_package("${prefix}" parent "${parent_installed}" "find_dependency(stlab-leaf 1.0.0)")
    check_package("${prefix}" leaf "${leaf_installed}" "")
    if(parent_installed AND leaf_installed)
        set(consumer "${case_root}/consumer")
        file(MAKE_DIRECTORY "${consumer}")
        file(COPY "${CMAKE_CURRENT_LIST_DIR}/fixtures/consumer/" DESTINATION "${consumer}")
        if(shared)
            set(expected_leaf_type SHARED_LIBRARY)
        else()
            set(expected_leaf_type STATIC_LIBRARY)
        endif()
        run_command("${CMAKE_COMMAND}" -S "${consumer}" -B "${consumer}/build" -G Ninja
            "-DCMAKE_PREFIX_PATH=${prefix}" "-DTOOLKIT_SOURCE=${toolkit_source}"
            "-DEXPECTED_LEAF_TYPE=${expected_leaf_type}")
        run_command("${CMAKE_COMMAND}" --build "${consumer}/build")
        if(WIN32)
            include("${consumer}/build/runtime-dlls.cmake")
            if(shared AND NOT runtime_dlls)
                message(FATAL_ERROR "The installed shared leaf must provide a runtime DLL")
            elseif(NOT shared AND runtime_dlls)
                message(FATAL_ERROR "A static leaf must not require a runtime DLL")
            endif()
            foreach(dll IN LISTS runtime_dlls)
                cmake_path(IS_PREFIX prefix "${dll}" NORMALIZE installed)
                get_filename_component(filename "${dll}" NAME)
                foreach(directory tests examples)
                    if(NOT installed OR NOT EXISTS "${consumer}/build/client apps/${directory}/${filename}")
                        message(FATAL_ERROR "Installed DLL was not deployed beside ${directory}: ${dll}")
                    endif()
                endforeach()
            endforeach()
            if(shared)
                run_command("${CMAKE_COMMAND}" "-DCPP_LIBRARY_RUNTIME_DLLS=${runtime_dlls}"
                    "-DCPP_LIBRARY_RUNTIME_DESTINATION=${prefix}/bin"
                    -P "${toolkit_source}/cmake/cpp-library-copy-runtime-dlls.cmake")
            endif()
        endif()
        run_command("${ctest}" --test-dir "${consumer}/build" --output-on-failure)
    endif()
    message(STATUS "PASS ${name}: parent=${parent_installed}, leaf=${leaf_installed}")
endfunction()

# Installs directory-local rules to prove a broken package does not poison its sibling.
function(run_invalid_case invalid clean target)
    set(case_root "${test_root}/invalid-${invalid}")
    set(source "${case_root}/source")
    set(binary "${case_root}/build")
    set(prefix "${case_root}/prefix")
    file(MAKE_DIRECTORY "${source}")
    file(COPY "${CMAKE_CURRENT_LIST_DIR}/fixtures/nested/" DESTINATION "${source}")
    run_command("${CMAKE_COMMAND}" -S "${source}" -B "${binary}" -G Ninja
        "-DTOOLKIT_SOURCE=${toolkit_source}"
        -DSTLAB_PARENT_INSTALL=ON -DSTLAB_LEAF_INSTALL=ON "-DINVALID_PACKAGE=${invalid}")
    run_command("${CMAKE_COMMAND}" --build "${binary}")
    set(parent_binary "${binary}")
    set(leaf_binary "${binary}/leaf")
    run_command("${CMAKE_COMMAND}" "-DCMAKE_INSTALL_PREFIX=${prefix}"
        -DCMAKE_INSTALL_LOCAL_ONLY=TRUE -P "${${clean}_binary}/cmake_install.cmake")
    if(clean STREQUAL "parent")
        check_package("${prefix}" parent TRUE "find_dependency(stlab-leaf 1.0.0)")
    else()
        check_package("${prefix}" leaf TRUE "")
    endif()
    execute_process(COMMAND "${CMAKE_COMMAND}" "-DCMAKE_INSTALL_PREFIX=${prefix}"
        -DCMAKE_INSTALL_LOCAL_ONLY=TRUE -P "${${invalid}_binary}/cmake_install.cmake"
        RESULT_VARIABLE result OUTPUT_VARIABLE out ERROR_VARIABLE err)
    set(output "${out}\n${err}")
    set(diagnostic "cpp-library: Cannot install stlab-${invalid} - untracked dependencies detected:")
    string(FIND "${output}" "${diagnostic}" found)
    string(FIND "${output}" "  - ${target}" dependency_found)
    string(FIND "${output}" "Cannot install stlab-${clean}" contaminated)
    if(result EQUAL 0 OR found LESS 0 OR dependency_found LESS 0 OR NOT contaminated EQUAL -1)
        message(FATAL_ERROR "Expected only ${invalid} diagnostic '${diagnostic}' and '${target}':\n${output}")
    endif()
    check_package("${prefix}" "${invalid}" FALSE "")
    message(STATUS "PASS invalid-${invalid}: isolated '${diagnostic}' / '${target}'")
endfunction()

# Separate child script invocations let all expected RED failures be inspected in one run.
if(DEFINED CASE)
    if(CASE STREQUAL "both")
        run_case(both TRUE TRUE OFF -DSTLAB_PARENT_INSTALL=ON -DSTLAB_LEAF_INSTALL=ON -DLEGACY_OFF=ON)
    elseif(CASE STREQUAL "both-shared")
        run_case(both-shared TRUE TRUE ON -DSTLAB_PARENT_INSTALL=ON -DSTLAB_LEAF_INSTALL=ON)
    elseif(CASE STREQUAL "parent-only")
        run_case(parent-only TRUE FALSE OFF -DSTLAB_PARENT_INSTALL=ON -DSTLAB_LEAF_INSTALL=OFF)
    elseif(CASE STREQUAL "leaf-only")
        run_case(leaf-only FALSE TRUE OFF -DSTLAB_PARENT_INSTALL=OFF -DSTLAB_LEAF_INSTALL=ON)
    elseif(CASE STREQUAL "custom-defaults")
        run_case(custom-defaults TRUE FALSE OFF)
    elseif(CASE STREQUAL "legacy-on")
        run_case(legacy-on TRUE TRUE OFF -DLEGACY_OPTIONS=ON -DSTLAB_INSTALL=ON)
    elseif(CASE STREQUAL "legacy-off")
        run_case(legacy-off FALSE FALSE OFF -DLEGACY_OPTIONS=ON -DSTLAB_INSTALL=OFF)
    elseif(CASE STREQUAL "legacy-defaults")
        run_case(legacy-defaults TRUE TRUE OFF -DLEGACY_OPTIONS=ON)
    elseif(CASE STREQUAL "invalid-parent")
        run_invalid_case(parent leaf UnknownParent::dep)
    elseif(CASE STREQUAL "invalid-leaf")
        run_invalid_case(leaf parent UnknownLeaf::dep)
    elseif(CASE STREQUAL "missing-option")
        set(source "${test_root}/missing-option/source")
        file(MAKE_DIRECTORY "${source}")
        file(COPY "${CMAKE_CURRENT_LIST_DIR}/fixtures/nested/" DESTINATION "${source}")
        execute_process(COMMAND "${CMAKE_COMMAND}" -S "${source}" -B "${test_root}/missing-option/build"
            -G Ninja "-DTOOLKIT_SOURCE=${toolkit_source}" -DMISSING_INSTALL_OPTION=ON
            RESULT_VARIABLE result OUTPUT_VARIABLE out ERROR_VARIABLE err)
        set(diagnostic "cpp_library_setup: INSTALL_OPTION requires a value")
        string(FIND "${out}\n${err}" "${diagnostic}" found)
        if(result EQUAL 0 OR found LESS 0)
            message(FATAL_ERROR "Expected diagnostic '${diagnostic}':\n${out}\n${err}")
        endif()
        message(STATUS "PASS missing-option: ${diagnostic}")
    else()
        message(FATAL_ERROR "Unknown test case: ${CASE}")
    endif()
    return()
endif()

foreach(case both both-shared parent-only leaf-only custom-defaults legacy-on legacy-off legacy-defaults
    invalid-parent invalid-leaf missing-option)
    execute_process(COMMAND "${CMAKE_COMMAND}" "-DCASE=${case}" "-Dtest_root=${test_root}"
        -P "${CMAKE_CURRENT_LIST_FILE}"
        RESULT_VARIABLE result OUTPUT_VARIABLE out ERROR_VARIABLE err)
    message(STATUS "${case}:\n${out}")
    if(NOT result EQUAL 0)
        message(STATUS "FAIL ${case}:\n${err}")
        list(APPEND failed_cases "${case}")
    endif()
endforeach()
file(REMOVE_RECURSE "${test_root}")
if(failed_cases)
    message(FATAL_ERROR "Nested install cases failed: ${failed_cases}")
endif()
message(STATUS "All 11 nested install cases passed!")
